### ISSUE TITLE
Improve chart display  - responsive charts

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/bie-plugin#1]
Currently rendering poorly

<img width="922" alt="screenshot 2015-07-22 14 43 07" src="https://cloud.githubusercontent.com/assets/444897/8826719/5a2823c2-3080-11e5-93c3-25dec5e66085.png">

Examples:

http://codepen.io/shoogledesigns/pen/BfLkA
http://jsfiddle.net/toddlevy/c59HH/

**Comment by nickdos** [comment]
@djtfmartin has created a grails plugin for charts - suggest we use this (if not already doing so).

https://github.com/AtlasOfLivingAustralia/ala-charts-plugin

**Comment by djtfmartin** [comment]
closing. this is done
