### ISSUE TITLE
Accepted name for some synonyms not showing proper name

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-plugin#112]
Eg. https://bie.ala.org.au/species/http%3A//id.biodiversity.org.au/instance/apni/941887

A search for "Polyscias sambucifolia subsp. 1" gives "Polyscias sambucifolia subsp. 1 (accepted name Polyscias subsp.)" when the accepted name is "Polyscias sambucifolia subsp. Long leaflets (P.G.Neish 208)"

**Comment by nickdos** [comment]
Duplicate of #114
