### ISSUE TITLE
Iterate over biocache-service occurrences/taxaCount to take advantage of caching

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/bie-plugin#117]
There are calls to`` biocache-service`` ``occurrences/taxaCount`` currently that bundles many taxa into a single ``HTTP POST`` request, which is uncacheable by ``biocache-service``, so it needs to execute a query on solr everytime (unless it is in other caches below).

https://github.com/AtlasOfLivingAustralia/bie-service/blob/master/src/main/java/org/ala/web/SearchController.java#L379-L391

If there were a set of ``HTTP GET`` requests for a single taxa each time, ``biocache-service`` could cache the results at the nginx level to avoid requests down to solr when the taxa has been queried recently, reducing the load on the fairly fragile solr cloud setup.

**Comment by ansell** [comment]
Not sure which repository this is best suited to or where the current code for it is, the only code I could see using a POST to taxaCount was in bie-service, which appears to be deprecated.

**Comment by ansell** [comment]
An example of a query from the log files that matches the HTTP POST queries to ``bie.ala.org.au`` is:

```
172.30.0.162 - - [24/Aug/2018:11:34:38 +1000] "POST /ws/occurrences/taxaCount?guids=NZOR-4-131127%2CNZOR-4-64188%2CNZOR-4-4495%2CNZOR-4-102214%2Curn%3Alsid%3Aindexfungorum.org%3Anames%3A11060%2CNZOR-4-116551%2Curn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Aaa1017d5-8ab7-44af-a2c9-b7910758d673%2CNZOR-4-3104%2CNZOR-4-104362%2CNZOR-4-8900&separator=%2C HTTP/1.1" 200 242 "-" "Java/1.8.0_181" "52.62.134.156"
```

**Comment by nickdos** [comment]
The only reference to `taxaCounts` is https://github.com/AtlasOfLivingAustralia/bie-plugin/blob/master/grails-app/assets/javascripts/species.show.js#L156 which is doing a GET with a single GUID. So I'll move this to `bie-index`.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/bie-index#211
