### ISSUE TITLE
Search for voucher names return confused results

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-plugin#119]
Moved from https://github.com/AtlasOfLivingAustralia/bie-index/issues/199 It should be possible to send a query directly to bie-index. Escaping has to happen in the search box.

Possibly a result of the parentheses being interpreted by the solr query? For example,

https://bie.ala.org.au/search?q=Dillwynia+sp.+trichopoda returns sensible results.

https://bie.ala.org.au/search?q=Dillwynia+sp.+trichopoda+%28Maiden+%26+Boorman+s.n.+40290%29 does not

https://bie.ala.org.au/search?q=Dillwynia+sp.+trichopoda+Maiden+Boorman+s.n.+40290 is sort of OK.

The voucher name appears in the scientific name for search purposes, since the authorship is given as NSW Herbarium

**Comment by TaniaGLaity** [comment]
appears fixed using the above examples
