### ISSUE TITLE
Species pages representative image - enhancement

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#120]
See support ticket https://support.ehelp.edu.au/helpdesk/tickets/23307

Minor enhancement to allow links to species pages on the ALA FaceBook page, to include the main image of that species.

Currently FB is pulling in a "No image found" image that is loaded 'in place of' the distribution image map (which has CSS `display:none`). The species image appears to NOT be used, due to the fact that image is loaded via AJAX code. 

A possible fix is to get the representative image URL at the controller level and then have that image loaded directly in the GSP, as opposed to via AJAX. This may have performance impacts so the code that looks up the imageUrl should have a short timeout and not prevent the page from loading if not available. A better solution would be to pull it out of the SOLR index - might already be in there, I've not checked.

We should alos follow this practice: https://stackoverflow.com/questions/19632323/default-website-image-for-social-sharing

```
<meta property="og:image" content="http://example.com/logo.jpg">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1024">
<meta property="og:image:height" content="1024">
```

**Comment by Rita-C** [comment]
@nickdos @charvolant , code checked in for review.

**Comment by nickdos** [comment]
Deployed to prod.

**Comment by nickdos** [comment]
Comms has asked that species page work with both FB and Twitter link generators, based on this article: https://www.freecodecamp.org/news/how-to-avoid-the-shaming-look-your-site-has-on-twitter-and-facebook-f2e8f4be568d/

Re-opening this issue to enhance existing changes with the following:

- [ ] add additional FB OpenGraph tags:  `og:url`, `og:type`, `og:title`, `og:description`
- [ ] add Twitter tags: `twitter:card`,`twitter:image`,`twitter:image:alt`, `twitter:description` (note slightly different `meta` tag syntax)

`title`suggestion "Species: Red Kangaroo (Osphranter rufus)"
`description` suggestion "Atlas of Living Australia (ALA) species page for the Red Kangaroo."

Note: "Atlas of Living Australia (ALA)" should use the 2 config vars so not to break LA sites and `i18n` text substitutions should also be used.

**Comment by Rita-C** [comment]
@nickdos given that scientific name is always available, common name is not, can I suggest:  
`title` "Species: Osphranter rufus (Red Kangaroo)"
`description`  "Atlas of Living Australia (ALA) species page for the Osphranter rufus"

**Comment by nickdos** [comment]
QA - looks good, proceed to CAB 🚕

**Comment by nickdos** [comment]
Tried testing this with test server using https://cards-dev.twitter.com/validator but got error `ERROR: Fetching the page failed because it's denied by robots.txt.`. We don't want to open the test server to being indexed by Google, so leaving testing until deployed to production as worse case scenario is it falls back to using FB tags which provide a preview icon already.

**Comment by nickdos** [comment]
Post prod deployment, this change is working as expected:

![image](https://user-images.githubusercontent.com/532845/78210088-bffb9680-74f4-11ea-9687-fcde09e820e6.png)
