### ISSUE TITLE
Species pages sending wrong query for alerts (emails)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#126]
See https://github.com/AtlasOfLivingAustralia/alerts/issues/40

2 bugs need fixing:

- [x] Missing `lsid:` in query
- [x] query is completely missing from the `query_path_forui` param.

`query_path_forui` param issue can be seen with this SQL query result:

`query_path` = `/ws/occurrences/search?q=http://id.biodiversity.org.au/node/apni/2896095&fq=first_loaded_date:[___DATEPARAM___%20TO%20*]&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record`
`query_path_forui` = `/occurrences/search?q=*:*&fq=first_loaded_date:[___DATEPARAM___%20TO%20*]&sort=first_loaded_date&dir=desc`

**Comment by ansell** [comment]
Is there anyway of manually triggering emails in alerts to test this?

**Comment by nickdos** [comment]
I just got some species pages alerts come through and they all look good so far.

**Comment by nickdos** [comment]
Deployed to prod today
