### ISSUE TITLE
Support separate biocache ws URL in generate alerts button handler

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/bie-plugin#127]
A future goal is to split ``biocache.ala.org.au`` and ``biocache-ws.ala.org.au`` so they don't need to rely on a single load balancer. There is a hardcoded ``/ws/`` context path in the generate alerts button handler currently that would be replaced with a context path and the biocache services host could be configurable.

https://github.com/AtlasOfLivingAustralia/bie-plugin/commit/c090b05993f598d9c5f6ef863ac8d534a38090cd#diff-dbb9cb6129246881e089cbd9ba786878R88

https://github.com/AtlasOfLivingAustralia/bie-plugin/commit/c090b05993f598d9c5f6ef863ac8d534a38090cd#diff-dbb9cb6129246881e089cbd9ba786878R90

This would also help with other bie deployments if they have separate ``biocache-hub`` and ``biocache-service`` DNS names or they aren't locating ``biocache-service`` at ``/ws/``.

**Comment by ansell** [comment]
This has been deployed to bie-test and is ready for QA

**Comment by Rita-C** [comment]
Tested as:
1. Checked JS on `https://bie-test.ala.org.au/`, it shows:
```
       $("#alertsButton").click(function(e) {
        e.preventDefault();
        var query = "Species: " + SHOW_CONF.scientificName;
        var searchString = "?q=lsid:" + SHOW_CONF.guid;
        var url = SHOW_CONF.alertsUrl + "/webservice/createBiocacheNewRecordsAlert?";
        url += "queryDisplayName=" + encodeURIComponent(query);
        url += "&baseUrlForWS=" + encodeURIComponent(SHOW_CONF.biocacheServiceUrl);
        url += "&baseUrlForUI=" + encodeURIComponent(SHOW_CONF.biocacheUrl);
        url += "&webserviceQuery=%2Foccurrences%2Fsearch" + encodeURIComponent(searchString);
        url += "&uiQuery=%2Foccurrences%2Fsearch" + encodeURIComponent(searchString);
        url += "&resourceName=" + encodeURIComponent("Atlas");
        window.location.href = url;
```

2. Created an alert
- Checked alert appeared on `My alert` page (on prod), 
- Tested `query.baseUrl + query.queryPath` returned "Could not find a healthy node to handle the request." intead of valid Json
- (https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:e9d6fbbd-1505-4073-990a-dc66c930dad6&fq=first_loaded_date:[2020-11-30T11%3A11%3A54Z%20TO%20*]&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record)
