### ISSUE TITLE
Removing filter results in 404

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#141]
https://bie.ala.org.au//search?q=&fq=rank:%22species%22#

click the remove filter link (x icon)at top of left column 

```
Current filters
Taxonomic rank: "species" (x)
```

which triggers this link/page: https://search/?q=&fq=

**Comment by nickdos** [comment]
I just realised the double slash in URL is the cause. I'm not sure how that got there but will close as "not an issue".

**Comment by ansell** [comment]
Some of the `//` links come from biocache. I tried to isolate them in kibana a few days ago, but it isn't easy because elasticsearch seems to ignore them.
