### ISSUE TITLE
BIE - UI - Species page - Display IEK Language and terms in header

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/bie-plugin#148]
Check repository, not sure if this should be in bie-generic or bie-ala.

As a user of the species pages
I want to know if there are any IEK terms in use for this species
So that I am aware IEK knowledge exists for this species

Background:
AS IEK knowledge becomes more valued and sought after, ALA is trying to showcase the IEK that exists and has been made available through our systems. Currently we are proposing to show any preferred common name first as there will always only be one of these. then IEK names can be shown in more prominent text in a section that will expand to accommodate the number of terms available.

Requirements:
1. IEK names (terms) will be displayed under the preferred common name for the taxon.
2. The common name should have smaller font, no bolding and be italic.
3. The language and the term will be displayed together separated by the word "in". E.g "garrawal in Rembarrnga" See mockup https://confluence.csiro.au/display/ALASD/Indigenous+language+names+for+plants+and+animals+in+ALA#IndigenouslanguagenamesforplantsandanimalsinALA-UIMockup
4. Formatting for language term and language name:
- Term should be italic and bold
- Language name should be bold
- Font size should be slightly smaller than Scientific Name
- If possible, more than 5 IEK names should be displayed in 2 columns, although if that means the language name needs to wrap, they should display in one column. (I assume this means on a small screen the second column will display underneath the first - please discuss if this makes no sense...)
5. the section containing IEK terms will expand to include all IEK terms applicable to the taxon
6. If no IEK terms are known to the ALA for the taxon, the section will not be displayed.

Do we need a separate story for the web services to get the names for the display?

**Comment by m-hope** [comment]
Need to talk with Doug/Nick to find out how the names are delivered and if there is anything specific that is needed to be done to identify/separate the IEK names (ie: do they need to be fetched separately, or do they come as vernacular names that have an IEK tag/identifier ... could the language code be used).  Otherwise this should just be a UI page edit???

**Comment by m-hope** [comment]
Specific task to complete: need to confirm that searching on an IEK language term will return a "Common Name" entry in the search results, however the reference should be "Indigenous Knowledge Name" not "Common Name".

**Comment by RobinaSanderson** [comment]
Code review and test by data management team, moving to ready to be released column for IEK project.
