### ISSUE TITLE
Species page: identify and fix any issues compared to current version

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#15]
_From @nickdos on April 4, 2016 0:26_

This task involves manually eye-balling as many species pages as possible to see if the new version is missing data, etc compared to the current prod version.

First check all the iconic species.
Next pick a good spread of species from the different major groups and sources.

_Copied from original issue: AtlasOfLivingAustralia/bie-index#58_

**Comment by pwscsiro** [comment]
Species Page - the view resolved at ../species.  For example [http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:b76f8dcf-fabd-4e48-939c-fd3cafc1887a#](url) 
The layout, navigation and styling may be different between old and new versions of the application, but the same data and textual information needs to be included and displayed in some form and existing functionality needs to be retained.

**Comment by pwscsiro** [comment]
Business Capability supported: Provide user/customer with information about a Species?
