### ISSUE TITLE
Encylopedia of Life returns wrong result

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-plugin#153]
For example, https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:4be6fe48-0b85-47e2-8673-1509103a9f4a returns an overview for Centrodoras (a catfish) not Centrodora. This seems to be a bizzarity of EoL search, since a search for Centrodora returns Centrodoras as the first result and Centrodora as the second.

Possible solution, check name actually matches before allowing it through to sully the web page..

**Comment by charvolant** [comment]
Another example, https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2896101 returns information about Acacia elata not Albizia procera

Within page request is https://bie.ala.org.au/externalSite/eol?s=Albizia+procera&f=Equisetopsida

Request to EOL is https://eol.org/api/search/1.0.json?q=Albizia+procera&page=1&exact=true&cache_ttl= returns Acacia elata as the first result.

**Comment by TaniaGLaity** [comment]
fixed above issues as link now to wikipedia by admins
