### ISSUE TITLE
Expert distribution maps not showing on species pages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#156]
E.g. Major Mitchell's Cockatoo

https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:0217f06f-664c-4c64-bc59-1b54650fa23d

Looks like there are two issues:

- [x] spatial-service is not allowing CORS requests
- [ ] bie-plugin is still requesting JSONP but spatial-service does not support it, so needs to be changed to plain JSON and CORS working (see above). See #116 .

**Comment by adam-collins** [comment]
This is a CORB issue that is fixed with https://github.com/AtlasOfLivingAustralia/bie-plugin/commit/94a7d22b03233abb5e523d4f36c5f38b3ad489f4

**Comment by Rita-C** [comment]
Hi @nickdos , could you please check if Adam's fix resolved the issue please?

**Comment by nickdos** [comment]
Expert dist are showing again, so closing.
