### ISSUE TITLE
Results from EoL coming back with encoded HTML

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-plugin#160]
See, for example.

![image](https://user-images.githubusercontent.com/4031353/60142542-9ee77600-97fd-11e9-9a1f-5d331076ee20.png)

Also, emdash characters appear to be getting squashed.

**Comment by charvolant** [comment]
Example
https://bie.ala.org.au/species/http:/id.biodiversity.org.au/node/apni/7692613

**Comment by charvolant** [comment]
As another example, https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2886851 produces mush text. Possibly an encoding error. 
<img width="750" alt="Screen Shot 2019-09-02 at 11 58 31 am" src="https://user-images.githubusercontent.com/4031353/64086001-18a95c00-cd79-11e9-9456-8c93a8b29ccf.png">

**Comment by charvolant** [comment]
The direct HTML from EoL comes back as `produces stems 17–59 cm (<span>6<span> </span><sup>3</sup>⁄<sub>4</sub></span>–<span>23<span>` From the look of it, the slash and dash are being incorrectly encoded.

**Comment by Rita-C** [comment]
Hi @charvolant, both example urls returned error, need an update?

**Comment by charvolant** [comment]
Try https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2888674 and https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2886851 
Both these look OK

**Comment by Rita-C** [comment]
can we close this ticket then @charvolant ?

**Comment by charvolant** [comment]
@Rita-C I would think so, everything looks good -- until the next thing that trips us up :)
