### ISSUE TITLE
Add search start page for taxa (species) searches

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#165]
The new WP navigation menu has an option `Search species` that goes to https://bie.ala.org.au/ but this allows searching on all content types, not just species.

I propose we add https://bie.ala.org.au/species or https://bie.ala.org.au/taxa that has the `fq` pre-populated so it only searches species/taxa pages.

**Comment by charvolant** [comment]
* [ ] Add search index page that filters on taxon
* [ ] Make species search page autocomplete
* [ ] i18n for search pages and make text distingush between 'search' and 'search for species'
* [ ] Ensure ala-bie index pages reflect the search style
* [ ] Point species search to https://bie.ala.org.au/species

**Comment by charvolant** [comment]
Changes to bie-plugin and ala-bie ready for review
