### ISSUE TITLE
Species Page - identify features of current production version

### ISSUE THREAD

**Issue by pwscsiro** [AtlasOfLivingAustralia/bie-plugin#17]
List the features of the current functionality by observation

**Comment by pwscsiro** [comment]
Thinking about what the best format to capture this information is. Trying Cucumber features in the structure: serenity-bie
	src
		main
		test
			resources
				features
					alabanner
						alaBanner.feature
					alafooter
						footer.feature
					alaimageviewer
						imageviewer.feature
					species
						authorisation.feature
						classification.feature
						gallery.feature
						header.feature
						literature.feature
						names.feature
						overview.feature
						records.feature
						sequences.feature
						sidebar.feature

This automatically organises the information in a code friendly, Agile friendly and test friendly format. It is flexible as well in that these files are written in English text and therefore can be stored anywhere - either as part of the code base, as part of a word document or on a wiki. They also open up the possibility of test automation in that they can be converted into either Spock , Geb or Cucumber tests as they follow BDD format of given, when, then.

**Comment by pwscsiro** [comment]
Example Feature file:
![overview feature](https://cloud.githubusercontent.com/assets/17239936/14446396/129233ba-0099-11e6-990b-64395f722c48.png)

**Comment by pwscsiro** [comment]
Here is a summary of identified Features, full details are in ../src/test/resources/features
Species
1.0 Authorisation
	1.1 Email Alert 
	1.2 Completion of Login  (new)
	1.3 Record a sighting
2.0 Classification
	2.1 Working classification
	2.2 Species
	2.3 Subspecies
3.0 Gallery
	3.1 Type images
	3.2 Speciman Images
	3.3 Load more images - specimen
	3.4 Images
	3.5 Load more images - general
	3.6 View an image
	3.7 Show image details
	3.8 Videos
	3.9 Video details
	3.10 View video
4.0 Header
	4.1 Breadcrumb trail
	4.2 Species scientific name
	4.3 Species common name
	4.4 Record a sighting
	4.5 Request email alert
5.0 Literature
	5.1 Name references from Biodiversity Heritage Library (BHL)
	5.2 Reference count - BHL
	5.3 Display Reference details - BHL
	5.4 Link to source reference name - BHL
	5.5 Page thumbnail - BHL
	5.6 Results navigation - BHL
	5.7 Results pagination - BHL
	5.8 Reference Summary - BHL
	5.9 Name references from Trove
	5.10 Reference count - Trove
	5.11 Display details - Trove
	5.12 Record name link - Trove
	5.13 Results navigation - Trove
	5.14 Results pagination - Trove
6.0 Names
	6.1 Accepted Name
	6.2 Synonyms
	6.3 Common Names
7.0 Overview
	7.1 Compiled Distribution Map
	7.2 Primary Image
	7.3 Occurrence records Map
	7.4 Sounds
	7.5 Play Audio
	7.9.6 Audio details
	7.7 View records list
	7.8 Map & analyse records
	7.9 Description
	7.10 Online resources
	7.11 Species list 
8.0 Records
	8.1 Occurrence records
	8.2 Charts
	8.3 Chart links
	8.4 No charts available (new)
	8.5 Record maps from other sources
9.0 Sequences
	9.1 Genbank results
	9.2 Number of items
	9.3 Link to data listing
	9.4 Record details
	9.5 Record details link
10.0 Sidebar
	10.1 Name source
	10.2 Rank
	10.3 Data links
	10.4 Species presence
	10.5 Conservation status
11.0 Imageviewer
	11.1 Display image
	11.2 Navigation
	11.3 Navigation controls
	11.4 Detail summary
	11.5 View details
	11.6 Close viewer
12.0 Banner
	12.1 Organisation Logo
	12.2 Organisation Name
	12.3 Organisation Apps
	12.4 Organisation Info
	12.5 Search Box
	12.6 User settings
13.0 Footer
	13.1 Website description, purpose
	13.2 Attribution - NCRIS
	13.3 Attribution - GBIF
	13.4 Copyright Licence
	13.5 Citizen Science
	13.6 Website Features
	13.7 Website data
	13.8 Contact us
	13.9 Social media
	13.10 Miscellaneous links

**Comment by TaniaGLaity** [comment]
closing as duplicate
