### ISSUE TITLE
Update BHL link

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/bie-plugin#176]
The BHL direct links have been updated to point to `www.biodiversitylibrary.org`, but the other link still goes to the previous domain name:

`biodiversityheritagelibrary.com`

Found while investigating ticket 38253 on helpdesk

**Comment by elywallis** [comment]
Just noting that biodiversityheritagelibrary.com has never ever been the URL for BHL. Don't know how that got in to code in ALA. If you find that incorrect URL anywhere please correct it.

**Comment by ansell** [comment]
@elywallis It does resolve to the same server, so at some point its DNS entry was created and pointed to that location.

**Comment by charvolant** [comment]
In progress ... I'm not sure why there is an absolute link in there in the first place, since it should be coming from the config (which is correct).
