### ISSUE TITLE
Species page - list  features currently in new version

### ISSUE THREAD

**Issue by pwscsiro** [AtlasOfLivingAustralia/bie-plugin#18]
ala-bie and ala-bie-plugin are the intended replacements for the current production system and have been partially coded. There is also a live example at species.ala.scot

**Comment by pwscsiro** [comment]
List of features by observation in new version as at April - those in bold are implemented:
Species
1.0 Authorisation
**	1.1 Email Alert **
	1.2 Completion of Login  (new)
**	1.3 Record a sighting**
	1.4 Submit a photo (new)
2.0 Classification
**	2.1 Working classification**
	2.2 Species
**	2.3 Subspecies**
3.0 Gallery
	3.1 Type images
	3.2 Specimen Images
	3.3 Load more images - specimen
**	3.4 Images**
**	3.5 Load more images - general**
**	3.6 View an image**
	3.7 Show image details
	3.8 Videos
	3.9 Video details
	3.10 View video
4.0 Header
	4.1 Breadcrumb trail (removed - replaced with taxonomy breadcrumb trail)
**	4.2 Species scientific name**
**	4.3 Species common name**
**	4.4 Record a sighting (moved to Overview)**
**	4.5 Request email alert (moved to Overview)**
5.0 Literature
	5.1 Name references from Biodiversity Heritage Library (BHL)
	5.2 Reference count - BHL
	5.3 Display Reference details - BHL
	5.4 Link to source reference name - BHL
	5.5 Page thumbnail - BHL
	5.6 Results navigation - BHL
	5.7 Results pagination - BHL
	5.8 Reference Summary - BHL
	5.9 Name references from Trove
	5.10 Reference count - Trove
	5.11 Display details - Trove
	5.12 Record name link - Trove
	5.13 Results navigation - Trove
	5.14 Results pagination - Trove
**6.0 Names**
**	6.1 Accepted Name**
**	6.2 Synonyms**
**	6.3 Common Names**
**	6.4 Identifiers (new)**
7.0 Overview
	7.1 Compiled Distribution Map
**	7.2 Primary Image**
	7.3 Occurrence records Map
	7.4 Sounds
	7.5 Play Audio
	7.9.6 Audio details
	7.7 View records list
**	7.8 Map & analyse records (check - different implementation)**
**	7.9 Description**
**	7.10 Online resources**
**	7.11 Species list (check as heading is missing)**
**	7.12 Biology (new feature)**
**	7.13 Data providers (new feature)**
**	7.14 Submit a photo (new feature)**
8.0 Records
**	8.1 Occurrence records**
**	8.2 Charts (enhanced to By habitat, by collection, By data partner, By dataset, decade, month, since 1990)**
**	8.3 Chart links (check By habitat link)**
	8.4 No charts available (new)
	8.5 Record maps from other sources
**	8.6 Click through to view map of occurrences (moved from click through on pie chart)**
**9.0 Sequences**
**	9.1 Genbank results**
**	9.2 Number of items**
**	9.3 Link to data listing**
**	9.4 Record details**
**	9.5 Record details link**
10.0 Sidebar  (not present in new version, data distributed elsewhere)
	10.1 Name source (moved to Header)
	10.2 Rank (moved to Header)
	10.3 Data links 
	10.4 Species presence
	10.5 Conservation status (present in Scotland, but moved to overview)
**11.0 Imageviewer**
**	11.1 Display image**
**	11.2 Navigation**
**	11.3 Navigation controls (image count is missing)**
**	11.4 Detail summary**
**	11.5 View details**
**	11.6 Close viewer**
**12.0 Banner (organisation specific)**
**	12.1 Organisation Logo**
**	12.2 Organisation Name**
**	12.3 Organisation Apps**
**	12.4 Organisation Info**
**	12.5 Search Box**
**	12.6 User settings**
**13.0 Footer (organisation specific)**
**	13.1 Website description, purpose**
**	13.2 Attribution - NCRIS**
**	13.3 Attribution - GBIF**
**	13.4 Copyright Licence**
**	13.5 Citizen Science**
**	13.6 Website Features**
**	13.7 Website data**
**	13.8 Contact us**
**	13.9 Social media**
**	13.10 Miscellaneous links**
**14.0 Data Providers (new panel)**

NB this list is compiled through observation, not automated testing.

**Comment by djtfmartin** [comment]
closing. no longer seems relevant
