### ISSUE TITLE
Species Page - features to be added

### ISSUE THREAD

**Issue by pwscsiro** [AtlasOfLivingAustralia/bie-plugin#19]
Compare the features from issue #17  and #18  and list differences. Features are documented further in the source code at ../test/resources/features

**Comment by pwscsiro** [comment]
Features to be added or investigated further:
1.0 Authorisation
 1.2 Completion of Login (new) - sometimes the user is not where they expect to be after login
 2.0 Classification
 2.2 Species - highlight where the current record sites in the heirarchy
 3.0 Gallery - check whether type, specimen images and videos are working and add if necessary
3.1 Type images
3.2 Specimen Images
3.3 Load more images - specimen
 3.8 Videos
3.9 Video details
3.10 View video
4.0 Header - verify change in breadcrumb usage
4.1 Breadcrumb trail (removed - replaced with taxonomy breadcrumb trail)
5.0 Literature - implement
5.1 Name references from Biodiversity Heritage Library (BHL)
5.2 Reference count - BHL
5.3 Display Reference details - BHL
5.4 Link to source reference name - BHL
5.5 Page thumbnail - BHL
5.6 Results navigation - BHL
5.7 Results pagination - BHL
5.8 Reference Summary - BHL
5.9 Name references from Trove
5.10 Reference count - Trove
5.11 Display details - Trove
5.12 Record name link - Trove
5.13 Results navigation - Trove
5.14 Results pagination - Trove
7.0 Overview - check whether these features are implemented and if not implement them
7.1 Compiled Distribution Map
7.3 Occurrence records Map
7.4 Sounds
7.5 Play Audio
7.9.6 Audio details
7.7 View records list
 8.0 Records - check and implement as necessary
 8.4 No charts available (new)
8.5 Record maps from other sources
10.0 Sidebar (not present in new version, data distributed elsewhere) - analysis and implementation
10.1 Name source (moved to Header)
10.2 Rank (moved to Header)
10.3 Data links
10.4 Species presence
10.5 Conservation status (present in Scotland, but moved to overview)

**Comment by TaniaGLaity** [comment]
out of date and many of these have been addressed / no longer relevant / captured in other issues
