### ISSUE TITLE
Block links to some wikipedia pages 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#195]
Triggered by support ticket https://support.ehelp.edu.au/a/tickets/41909.

EOL was contacted and they also have an automated scraping service that makes it difficult to block particular Wikipedia pages. So best approach seems to be to create a black list of URLs that we check for and block on species pages, for content coming from EOL.

~Suggest we also sanitise HTML and remove inline CSS, that also creeps into some pages ([example](https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2887403)). Biocache uses `org.apache.commons.lang.StringEscapeUtils.unescapeHtml()` to do this ([see code](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/taglib/au/org/ala/biocache/hubs/OccurrenceTagLib.groovy#L928)).~

Also see AtlasOfLivingAustralia/bie-plugin/issues/181

**Comment by nickdos** [comment]
Moved to waiting for over shutdown

**Comment by Rita-C** [comment]
@nickdos , code ready for review at:
1. https://upsource.ala.org.au/bie-plugin/review/BP-CR-3
2. https://github.com/AtlasOfLivingAustralia/ala-install/commit/21c217be6eeb84ebd648e61ddee22586dc0dc6e0
3. https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/364ed56194b551113980226f1689d563ae2194a7

**Comment by nickdos** [comment]
I've QA'ed those code changes. Only thing I couldn't find was the ansible source file that gets copied into  `/data/ala-bie/config/contentToUpdate.properties`.

**Comment by Rita-C** [comment]
Good catch :)
I didn't update ansible for that due to the content of the file. But I could add a template I suppose.

**Comment by Rita-C** [comment]
Move back to in-progress:
Museum Victory requested to remove certain EOL context from "Pseudechis porphyriacus, the red-bellied black snake" page.

**Comment by timhicks-ala** [comment]
Following up on the helpdesk ticket - if this issue is Done (in production), should it be closed?

**Comment by Rita-C** [comment]
> Following up on the helpdesk ticket - if this issue is Done (in production), should it be closed?

Yes, please close the helpdesk ticket.
