### ISSUE TITLE
Large species images are 404

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#198]
E.g. https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:f9eb417b-2de3-48ac-ba4e-1d438f0cb323

The main image, which is shownabove the smaller thumbnail images, is showing missing image icon (404). The page is attempting to load the URL `/image/proxyImageThumbnailLarge?imageId=2ce95881-0217-411d-9442-27f8bb5c0f97`, which is being resolved to `https://bie.ala.org.au/image/proxyImageThumbnailLarge?imageId=2ce95881-0217-411d-9442-27f8bb5c0f97` and throws 404.

The thumbnail are requesting the URL `https://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=1f543aad-5a6b-4c08-af8a-539a9c9ec147` which suggests the main image URL is missing the `image-service` URL prefix of `https://images.ala.org.au`.

**Comment by Rita-C** [comment]
in bie-test for QA @nickdos
