### ISSUE TITLE
search results for variety not working

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/bie-plugin#199]
https://bie.ala.org.au//search?q=Halgania+cyanea+var.+Charleville+%28R.W.Purdie%2B+111%29

selecting this: Halgania cyanea var. Charleville (R.W.Purdie+ 111) Qld Herbarium in the search results throws an error https://bie.ala.org.au/species/Halgania%20cyanea%20var.%20Charleville%20(R.W.Purdie+%20111)

**Comment by Rita-C** [comment]
bie currently generates search result link using linkIdentifier (over guid) if it exists for readability purpose. The result page throws error if the linkIdentifier contains irregular characters.

Discussed with @charvolant , decided to rectify this issue in bie-index (https://github.com/AtlasOfLivingAustralia/bie-index/issues/255).

**Comment by nickdos** [comment]
@Rita-C can you QA this on test server? @charvolant  says its been deployed.

**Comment by Rita-C** [comment]
Ok

**Comment by charvolant** [comment]
Pull request didn't properly go into travis build. Now showing correct behaviour

https://bie-test.ala.org.au/search?sortField=&dir=desc&q=Halgania+cyanea

**Comment by Rita-C** [comment]
All good @charvolant , moved to "Ready for CAB".
