### ISSUE TITLE
Sanitise EOL HTML

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/bie-plugin#200]
Ticket split from #195

Suggest we sanitise EOL HTML and remove inline CSS, that also creeps into some pages ([example](https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2887403)). Biocache uses `org.apache.commons.lang.StringEscapeUtils.unescapeHtml()` to do this ([see code](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/taglib/au/org/ala/biocache/hubs/OccurrenceTagLib.groovy#L928)).

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/bie-plugin/review/BP-CR-4.

**Comment by Rita-C** [comment]
@nickdos , could you review the fix please?

**Comment by TaniaGLaity** [comment]
see comments above - closed issue
