### ISSUE TITLE
Image voting - implement sorting by votes or hide completely

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#207]
The image voting mechanism in the gallery appears to have no effect on the order images are displayed.  
- [ ] investigate to see if vote numbers do have an effect. 
- [ ] If they don't (as suspected), then look into how much work it would be to implement this (sorting photos in each section by votes and then by dataset (current method)
- [ ] if task is too big/complex, then hide the voting buttons via config var, so they can be turned back on in the future and create detailed issue for this task (tag with species-page-refresh-project).

**Comment by timhicks-ala** [comment]
If voting is difficult to implement, a possible way to improve images might be to prioritise those from certain data resources (eg iNaturalist, where identifications are confirmed from submitted photos), and/or from users with large numbers of submissions (who as enthusiasts are more likely to take clear photos).

We could also filter preserved specimen records and/or trap photos (eg DigiVol) further down the list, and I'm sure there's other ways we could use the existing data to guess whether a photo attached to a record is likely to be a "good" one or not.

**Comment by nickdos** [comment]
@timhicks-ala we already have some prioritisation of images from certain datasets in the code but it could probably be improved. I'm thinking this should be part of the species pages refresh project I mentioned on Slack (@elywallis is champion of).

**Comment by ansell** [comment]
Some background for this is at:

https://github.com/AtlasOfLivingAustralia/bie-index/issues/36

**Comment by nickdos** [comment]
I think this might be hard...

One possible way to achieve this is to first query biocache and get back a list of `imageID`s or `occurrenceID`s and then query image-service with that list and ask for the sort order to be by "votes". Then use that list as the basis for displaying images in the gallery.

**Comment by charvolant** [comment]
The current automatic image allocation can be set up to prioritise certain sources via boosts. See https://github.com/AtlasOfLivingAustralia/bie-index#image-scans (ignore the lists element, which is a hard override; the boosts element allows something like data_resource_uid:dr1234^100 for soft preferences.

**Comment by nickdos** [comment]
According to https://github.com/AtlasOfLivingAustralia/bie-index#image-scans, the `image-scan` process only seems to pick a representative image for taxa that don't have one defined in the species list "Preferred images" list.

This issue is more about the sorting of all images that appear in the Gallery tab, which is an AJAX request that happens at page display run-time.

**Comment by Rita-C** [comment]
Investigation notes:
The embedded `images-client-plugin` in `bie-plugin` allows voting on images. `images-client-plugin` sends collected data (key value pair [like/dislike: '567'], '567' is the user id) to `image-service`.  The `image-service` stores received data into `image_meta_data_item` table as a `UserDefined` entry then schedule a elasticsearch reindex on the image. for instance:
```
images=# select * from image_meta_data_item where id = 266625691;
    id     | version | image_id  | name |   source    | value 
-----------+---------+-----------+------+-------------+-------
 266625691 |       0 | 216345140 | like | UserDefined | 81552
(1 row)
```
Issues identified:
1. The call to `image-service` was updated to require an apiKey in July 2019, `images-client-plugin` was not updated accordingly.
2. Currently `image-service` seems to have received the data but no database update occurred, further investigation `image-service` is needed to find out the reason. Code at `imageService.setMetadataItems()`

**Comment by Rita-C** [comment]
linked ticket https://github.com/AtlasOfLivingAustralia/image-service/issues/112

**Comment by TaniaGLaity** [comment]
enabled admin function to prioritise or hide images
