### ISSUE TITLE
Change behaviour of BIE species page map

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/bie-plugin#222]
A feature suggestion spawned by helpdesk ticket 81489. The occurrence map on BIE pages can be panned and zoomed, so it is interactive, but looks visually identical to the map on Biocache pages even for the same species, where you are additionally able to click on and inspect individual records. The distinction between the two pages is difficult to grasp for casual users.

The suggestion is for the map on BIE pages to become static, and a clickable link to the Map tab on Biocache for the currently viewed species. It is also a little unusual having a link to "View interactive map" when the map in view is also somewhat interactive. A clearer, more intuitive split between the maps and functions might be useful to casual users of the ALA.

**Comment by TaniaGLaity** [comment]
being resolved with UX/ UI map design and enhancements
