### ISSUE TITLE
Calls to Encyclopedia of Life not handling homonyms correctly.

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-plugin#225]
Both pages for Scoparia 

https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A01b7a1bb-2687-4fc5-8479-eafe2d8e078f

and

https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2909378

contain EoL information from the plant side of the fence

The EoL calls are via

https://bie.ala.org.au/externalSite/eol?s=Scoparia&f=INSECTA for insects and https://bie.ala.org.au/externalSite/eol?s=Scoparia&f=Equisetopsida for plants. The f= entries are classes. However, correcting family to https://bie.ala.org.au/externalSite/eol?s=Scoparia&f=Crambidae produces the same results.

**Comment by charvolant** [comment]
As another example https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:3900f807-0399-4cf8-8a59-fd63174ddd5f

**Comment by charvolant** [comment]
Possible solution - blacklist for homonym and other problem cases?

**Comment by charvolant** [comment]
But wait, there's more https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:9cf0a9fa-4785-40c3-9474-b7aa388517e1

**Comment by charvolant** [comment]
Another example https://bie.ala.org.au/species/urn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A152dfc8d-8ea2-4dd2-86e2-92b375d1872c

**Comment by TaniaGLaity** [comment]
fixed all above examples as admin can select / changes Wikipedia url to correct one
