### ISSUE TITLE
Ensure informal ranks are included as child ranks in classification

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-plugin#228]
For example, https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:17c9fd64-3c07-4df5-a33d-eda1e065e99f#classification but from the other direction https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:591404da-cd0d-413f-b690-246e5ee7b7cb#classification

**Comment by Sherrin-ALA** [comment]
@TaniaGLaity : This appears to be happening in production - so can this be closed?

**Comment by TaniaGLaity** [comment]
@Sherrin-ALA  sure! I've been closing a bunch of old / already actioned items
