### ISSUE TITLE
Names sources are not linking to the corresponding external URL

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#245]
E.g. https://bie.ala.org.au//species/urn:lsid:biodiversity.org.au:afd.taxon:f984410a-ea99-4e73-8072-1d59340c299e#names On the "Names" tab, the name sources used to link to the external URL for that name (e.g. on AFD site) but they currently only link to the external source home page via the Collectory page. See screenshot:

![image](https://user-images.githubusercontent.com/532845/118608882-8b809200-b7fd-11eb-857f-0bb6bcedcfca.png)

**Comment by TaniaGLaity** [comment]
appears to be fixed
