### ISSUE TITLE
Autocomplete search for "saltwater crocodile" produces unexpected results

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/bie-plugin#249]
1. From ala.org.au, type "saltwater crocodile" in the search box
2. Autocomplete has two suggestions: "Salt-Water Crocodile,Saltwater Crocodile" and "Saltwater Crocodile,Salt-Water Crocodile"

![image](https://user-images.githubusercontent.com/57081387/122693338-c81c2f00-d27c-11eb-874f-b3dc20965508.png)

3. Both of these suggestions result in 337 search results (species pages etc) and 5.5m occurrence records.
4. These occurrence records include unexpected species including saltbush and plenty of seabirds.

https://biocache.ala.org.au/occurrences/search?q=Salt-Water+Crocodile%2CSaltwater+Crocodile

Reported in https://support.ehelp.edu.au/a/tickets/109262

**Comment by charvolant** [comment]
Closed. A new issue will be raised with the systems team to resolve the autocomplete issue.
