### ISSUE TITLE
Add data quality param `&qualityProfile=ALA` to biocache links

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#252]
Aad the `&qualityProfile=ALA` param to:

- [x] WMS map tile URLs
- [ ] ~View records URL~
- [ ] ~View interactive map URL (SP)~
- [ ] ~Receive alerts when new records are added (alerts)~
- [ ] ~Records tab -> charts (all chart URLs (might need change to chart plugin??)~
- [x] Images on image tab should be populated via call using DQ param
- [ ] ~Records tab -> 2 links on right side of page~
- [ ] ~Search results page: `Related Searches -> Occurrence records` link~
- [ ] ~Search results page: `Occurrences: NNN` link under each search result~
- [ ] ~Data partners tab -> links to DRs probably don't need it, but check anyway and make a judgement call~

**Comment by nickdos** [comment]
Code was hard to check due to backing out a lot of changes but seems OK. Should be done in PR next time, if more than 1-2 lines/files are changed.

**Comment by nickdos** [comment]
Map does not appear to be using the DQ param - deployed to prod this week. Investigate...

**Comment by nickdos** [comment]
Map is still showing records that do not appear when you view the same query on biocache, indicating filter is still not being applied. E.g. https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e9d6fbbd-1505-4073-990a-dc66c930dad6#tab_recordsView vs https://biocache.ala.org.au/occurrences/search?q=lsid%3Ahttps%3A%2F%2Fbiodiversity.org.au%2Fafd%2Ftaxa%2Fe9d6fbbd-1505-4073-990a-dc66c930dad6#tab_mapView. Note dots on western side of continent are different.

**Comment by adam-collins** [comment]
This appears to be working now. Closing.
