### ISSUE TITLE
VIC Conservation status not showing for Burhinus (Burhinus) grallarius

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/bie-plugin#253]
From https://support.ehelp.edu.au/a/tickets/111893

On this species page: https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:9e797cd8-e8a0-40ed-a2a6-6abecff8e21f

The state conservation status is shown on the left for NSW, NT, QLD, SA and WA, but not for VIC. There is VIC conservation status data for this species as it is shown in a box on the right, but the summary does not appear on the left.

![image](https://user-images.githubusercontent.com/57081387/126244437-10736e4e-d5cb-49d6-9fe7-b016e4dbc9db.png)

![image](https://user-images.githubusercontent.com/57081387/126244469-45ce35fc-4a04-4fda-a51e-3311f4faf1c7.png)

**Comment by peggynewman** [comment]
This was resolved some time ago. Closing.
