### ISSUE TITLE
Replace EOL data with Wikipedia

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#255]
This is a placeholder issue to store ideas for moving away from EOL pages as the source of text-based content on species pages, to Wikipedia or Wikispecies data. This will be handled as a mini project.

Wikipedia page: https://en.wikipedia.org/wiki/Chinese_water_dragon
Wikidata page: https://www.wikidata.org/w/api.php?action=wbgetentities&format=jsonfm&sites=enwiki&titles=Chinese%20water%20dragon&props=info%7Clabels%7Cdescriptions%7Cclaims&languages=en
DBPedia version: https://dbpedia.org/page/Chinese_water_dragon
Wikispecies version: https://species.wikimedia.org/wiki/Physignathus_cocincinus (different data?)

SO answer: https://stackoverflow.com/a/33862337/249327

**Comment by peggynewman** [comment]
Note previous ticket on this https://github.com/AtlasOfLivingAustralia/data-management/issues/499
