### ISSUE TITLE
Improve labels under map on species pages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#259]
The two large buttons under the occurrence map are slightly confusing for users, as the wording is not consistent with the naming scheme used elsewhere in the ALA.

![image](https://user-images.githubusercontent.com/532845/137425835-9461e462-86ba-4f74-9f6c-c779f78b8a5e.png)

I suggest the following changes:
- [ ] `View interactive map`  changes to 

 > View interactive map
 > in the Spatial Portal

- [ ] `View records` changes to 

 > View and download 
 > occurrence records 

This may result in the text breaking over 2 lines and I think that is fine.

**Comment by nickdos** [comment]
Any chance of this getting in before next CAB request, @charvolant ?

**Comment by TaniaGLaity** [comment]
fixed - closed issue
