### ISSUE TITLE
Species Overview panel - check whether these features are implemented and if not implement

### ISSUE THREAD

**Issue by pwscsiro** [AtlasOfLivingAustralia/bie-plugin#26]
Feature: Species - 7. Overview

  Scenario: 1. Compiled Distribution Map
    Given  distribution map is available
    When  the overview is displayed
    Then  the map for this species will be displayed together with a 'Compiled distribution map provided by ' acknowledgement displaying the name of the provider and linking to their website

  Scenario: 3. Occurrence records map
    Given  Occurrence data
    When  the overview is displayed
    Then  access to 'View records list' and 'Map & analyse records' will be avialable
 
 Scenario: 4. Sounds
    Given  sound data
    When  the overview is displayed
    Then  a Sounds heading and audio player control is displayed with 'Source:' label and link to more details

  Scenario: 5. Play Audio
    Given  sound data
    When  the audio control is started
    Then  the audio is played and audio control updated

  Scenario: 6. Audio details
    Given  sound data
    When  the View more details of this audio
    Then  the user is taken to the audio record in biocache
 
 Scenario: 7. View Records List
    Given  occurrence data
    When  the View Records List button is clicked
    Then  the user will be taken to the correct occurrences search results page in Biocache

**Comment by nickdos** [comment]
All good - closing
