### ISSUE TITLE
Species sidebar information - analyse and implement as necessary

### ISSUE THREAD

**Issue by pwscsiro** [AtlasOfLivingAustralia/bie-plugin#28]
The side bar has been removed in new version and some of its data relocated to other locations

Feature: Species - 10. Sidebar

  Scenario: 1. Name Source  (moved to Header)
    Given  name sources are available
    When  the species results page is displayed
    Then  name source and urls will be displayed

 Scenario: 2. Rank (moved to Header)
    Given  rank id is available
    When  the species results page is displayed
    Then  rank name will be displayed

 Scenario: 3. Data links
    Given  data links are available
    When  the species results page is displayed
    Then  data links will be displayed and will link to data in the matching format

 Scenario: 4. Species Presence
    Given species presence data
    When  the species results page is displayed
    Then  species presence icons and labels will be displayed such as 'Recorded in Australia', 'Terrestial Habitats'...

 Scenario: 5. Conservation Status  (present in Scotland, but moved to overview)
    Given   converstation status data
    When  the species results page is displayed
    Then  convservation status icon(s) and label(s) will be displayed, e.g. 'Least Concern' and linked through to the Conservation Status page

**Comment by nickdos** [comment]
implemented - closing and any suggestions/improvements will have to be new issues.
