### ISSUE TITLE
Floating Context menu

### ISSUE THREAD

**Issue by pwscsiro** [AtlasOfLivingAustralia/bie-plugin#30]
There was a suggestion that we provide a  menu to allow user to jump to different parts of panel to help navigate long scrolling lists. For example if the user is viewing the Literature panel on the species page and the implementation has data from both BHL and Trove, the context menu would have links to both to allow you to jump to either from anywhere in the panel without having to scroll.

So it will only be shown on the literature tab and it will float when page is scrolled so it stays in view. content will then be in a second column on the right so it doesn't overlap with the menu.

**Comment by pwscsiro** [comment]
Nick's wire frame prototype:
![context menu](https://cloud.githubusercontent.com/assets/17239936/14624762/e03b9270-0620-11e6-95fc-756911e5969e.png)

**Comment by pwscsiro** [comment]
Nick suggests using bootstrap 3 dropdown.js
http://getbootstrap.com/css/
http://getbootstrap.com/javascript/#dropdowns maybe?
Adam A has done something similar here: http://rawgit.com/AtlasOfLivingAustralia/front-end-static/master/ALA%20Website%20Recreation%20in%20B

**Comment by pwscsiro** [comment]
NB - suggest needs user acceptance testing as floating menus are not everyone's cup of tea

**Comment by pwscsiro** [comment]
Another option is straight CSS
http://www.quackit.com/css/codes/css_floating_menu.cfm
Relies on position:fixed which seems to have good browser support
http://caniuse.com/#search=position%3Afixed

**Comment by nickdos** [comment]
Implemented without floating it - seems good enough for now.
