### ISSUE TITLE
BIE - Ability to ingest data direct from Cybertracker/iTracker outputs

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/bie-plugin#37]
@sat01a commented on [Fri May 27 2016](https://github.com/AtlasOfLivingAustralia/profile-hub/issues/365)

**Comment by nickdos** [comment]
No details provided, so I have no ideas what this is asking for...

**Comment by TaniaGLaity** [comment]
duplicate issue has been closed  so closing this one too
