### ISSUE TITLE
Incorrect EOL data on taxon page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#47]
@nickdos commented on [Mon Aug 22 2016](https://github.com/AtlasOfLivingAustralia/bie-index/issues/96)

http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:332ce2f0-266a-46fe-878d-93ff5df76889

Pulling in snail information from EOL. Seems the EOL page (superfamily) has a synonym for the accepted name on this taxon. Possible fix is to check that the EOL pages is for the same rank as the calling ALA page.

---

@nickdos commented on [Wed Aug 24 2016](https://github.com/AtlasOfLivingAustralia/bie-index/issues/96#issuecomment-241910187)

AJAX issue in bie-plugin, so moving issue.

**Comment by nickdos** [comment]
There is still an outstanding bug related to the "Isotoma" page, where the plant taxon is returned despite requesting a filter for the animalia terms. I've logged an issue with OEL about this.

**Comment by nickdos** [comment]
Update on request sent to EOL:

> From: EOL Helpdesk <helpdesk@eol.org>
Date: Tue, Aug 23, 2016 at 11:24 PM
Subject: Re: A message to EOL: Technical questions (feedback or problems with functionality)
To: nickdos@gmail.com

>Dear Nick,
I’ve forwarded your message to a member of our team, who will be replying to you.  If you do not hear back from us in a day please reply to this address and I will escalate.
Thanks,
bob

>EOL Helpdesk
helpdesk@eol.org

**Comment by TaniaGLaity** [comment]
fixed by assigning correct Wikipedia pages to both genera
