### ISSUE TITLE
Search results page is producing bad biocache links

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/bie-plugin#53]
http://bie.ala.org.au/search?q=rkid_family:urn:lsid:biodiversity.org.au:afd.taxon:c68d2f83-664e-4e1a-8bc4-93d839d2d8e4 has a bad 'BHL Literature' and 'Occurrence records' search term. It also logs an error in biocache-service every time the page is opened because rkid_family is not a vaild biocache-service field and it attempts to find the total number of occurrences.

EDIT: link is coming the classification tab on species pages, via the button "Search for child taxa of foo":

![image](https://user-images.githubusercontent.com/532845/49846651-74653b00-fe20-11e8-8b33-c2cea3f03ca2.png)

**Comment by nickdos** [comment]
Looks to have been fixed.

**Comment by ansell** [comment]
I have seen the rkid_family error in the biocache-service logs recently, though possibly before your recent changes.

**Comment by nickdos** [comment]
Thanks @ansell - I now realised I wasn't testing the right thing - another example of not providing sufficient details in issue. I was looking at the biocache links under each hit and not the link at the top-right.

**Comment by adam-collins** [comment]
The URL in the issue was found in logs after following the source of the biocache-service log error. 

The page at the bie URL attempts to get the occurrence count for the query that contains rkid_family. The incorrect result (0) and incorrect link to biocache, https://biocache.ala.org.au/occurrences/search?q=rkid_family:urn:lsid:biodiversity.org.au:afd.taxon:c68d2f83-664e-4e1a-8bc4-93d839d2d8e4, is in the top right are of the page under "Related Searches".

Resolving this issue requires the translation of these BIE valid rkid_* search terms when used with biocache-service.

Upon further investigation the source of rkid_* search terms can be found on the 'classification' tab of species pages, e.g.  https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:c68d2f83-664e-4e1a-8bc4-93d839d2d8e4#classification On this page there are 3 button links on the right hand side, "Download child taxa of...", "Download species of ...", "Search for child taxa of...". Each of these 3 links contains rkid_family.

**Comment by nickdos** [comment]
Deployed to test - @adam-collins can you confirm the functionality is working as exected on test site: https://bie-test.ala.org.au/search?q=rkid_family:urn:lsid:biodiversity.org.au:afd.taxon:c68d2f83-664e-4e1a-8bc4-93d839d2d8e4 ?

**Comment by ansell** [comment]
For testing purposes, bie-test/bie-ws-test/biocache-test/biocache-ws-test (and test versions of the hubs, avh-test, asbp-test, ozcam-test) should all now be pointing back and forth between themselves. This is important because some queries round trip from bie->biocache->bie and it would make testing the new names impossible if they weren't linked together that way.

Testing between them on the query above looks okay to me
