### ISSUE TITLE
Formatting of common name search results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#58]
E.g. http://bie.ala.org.au/search?q=Barramundi

first 5 hits are all common names and they appear to be duplicates as they all have exactly the same text:

![image](https://cloud.githubusercontent.com/assets/532845/20377225/c149975a-ace1-11e6-9f89-3955a39889ab.png)

I suggest we inlcude the matching scientific name and its rank so that users can differentiate the results from each other. E.g.

> Common Name: Barramundi (family: LATIDAE)
Common Name: Barramundi (unknown_rank: Latidae, Ambassidae)

**Comment by charvolant** [comment]
Clicking through, they're all common names for different taxa. I agree that we should include some more explanatory information.

**Comment by nickdos** [comment]
Higher taxa information is not being sent from bie-index, so this requires either:

- adding higher taxa to output from bie-index
- doing separate (server-sde or AJAX) request for each name to determine the higher taxa values

**Comment by TaniaGLaity** [comment]
closed - scientific name now returned on common name search results
