### ISSUE TITLE
Search results page enhancements

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#6]
- [x] Fix display of facets box (box in a box looks bad)
- [x] Fix display of related searches (too big)
- [x] Download button display
- [x] Species page links with URLs broken
- [x] Species page links formatting/colours
- [x] Pagination links colours (remove blue) & centre on page (ala-bootstrap3 issue)
- [ ] <del>Add crumbtrail (ALA only?)</del>
- [x] facets more/less toggle is buggy
- [ ] facets not present: recorded in australia, life form, species (sub) group, <s>conservation status</s>
- [ ] facet order is random - fix to be same as prod
- [x] thumbnails not appearing in search results
- [x] occurrence counts in search results
- [x] site pages: show snippet with matched text (SOLR highlighting)
- [x] fix duplicate highlighting text

**Comment by djtfmartin** [comment]
The box in a box is specific to the ALA skin. 

See http://species.als.scot/search?q=

which is ala-bie with a different header and footer.

**Comment by TaniaGLaity** [comment]
closed as is covered by other issues
