### ISSUE TITLE
information from lists not showing on species pages in IE 9

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/bie-plugin#60]
None of the information sourced from lists that usually appears below the map on the right side of the species page is visible.  Rest of the page looks ok.

Department of Environment has IE 9 so would be good to cater for them if possible

**Comment by nickdos** [comment]
Some users are reporting that the gallery tab is not loading any images in IE 11. Might be jQuery version issue with `.clone()` or `.html()`.

**Comment by nickdos** [comment]
Fixed and available for testing on http://bie-dev.ala.org.au/ala-bie/

**Comment by M-Nicholls** [comment]
just responded to questions about lists on species pages from DoEE so they must be visible now.
