### ISSUE TITLE
Birdlife distribution maps copyright

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#72]
The blue BirdLife maps on species pages have no copyright so users would assume the CC license at bottom of the page would apply. They are actually copyright by BirdLife International and we should have that stated next to the maps.

**Comment by TaniaGLaity** [comment]
this should be included for all expert distribution maps

**Comment by TaniaGLaity** [comment]
moved to ala-bie-hub
