### ISSUE TITLE
Don't show charts for 0 records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#76]
Species pages, records tab...

if taxon has 0 records, then it shouldn't try to load all the charts or show the boxes on right side. 

http://bie.ala.org.au/species/NZOR-4-5168#records looks like this when it does:

![image](https://user-images.githubusercontent.com/532845/29198549-6afb8146-7e88-11e7-98d5-31e24c9daa58.png)

**Comment by ansell** [comment]
The fix to show a message but not attempt to render charts in this case looks good to me on bie-test.
