### ISSUE TITLE
Species pages enhancements & fixes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#8]
- [ ] clicking tabs causes page to "jump" (see fix in old version)
- [ ] Names tab - sources not showing (synonyms)
- [ ] Literature section is empty (JS error?)
- [ ] <s> tabs could be better styled? in a box maybe?</s>
- [ ] taxonomy breadcrumb formatting - improve styling
- [ ] taxonomy breadcrumb size - is currently wrapping over 2 lines for mammals, how to prevent this?
- [ ] data links are missing
- [ ] Does overview tab need a Bootstrap style ToC for section below the fold?
- [ ] Fix hard-coded statistics section (58% verified)

**Comment by TaniaGLaity** [comment]
closed as captured in other issues
