### ISSUE TITLE
ala-bootstrap3 dependency

### ISSUE THREAD

**Issue by reupost** [AtlasOfLivingAustralia/bie-plugin#98]
The ala-bootstrap3 dependency referenced in build.gradle seems to be missing:

This one is missing:
compile group: 'org.grails.plugins', name: 'ala-bootstrap3', version: '3.0.0-SNAPSHOT', changing: true

This works (but might not be appropriate, I'm not sure):
compile group: 'org.grails.plugins', name: 'ala-bootstrap3', version: '3.0.0', changing: true

**Comment by djtfmartin** [comment]
thanks @reupost 

i think there shouldn't be a dependency there. The ala-bootstrap3 plugin is pulled in by the webapp (as opposed to the plugin). 

See https://github.com/nbnuk/nbn-bie
