### ISSUE TITLE
Add links to BOLD on species pages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#99]
Under the "Sequences" tab, add a second source for Barcode of life (BOLD), similar to how the Literature tab manages multiple data sources.

Requires calling BOLD API - http://www.boldsystems.org/index.php/resources/api?type=webservices using the scientific name (and synonyms?)

E.g. http://www.boldsystems.org/index.php/API_Public/specimen?taxon=Macropus|Pogona&format=json

**Comment by elywallis** [comment]
There are 255,855 records in BOLD that come back on a query for "Australia". Many of the samples were collected in Australia or are from Australian species so a link to species pages makes sense.
There are lots of barcode records that could be linked to vouchered specimens in the Biocache as well - e.g. from ANIC, ANFC, Aus Mus, WAM etc. I will raise this at FCIG and see if I can get any takers for setting up links between specimens and BOLD as we've done for specimens and tissue samples. Same will also apply for GenBank sequences linked to the tissue that the DNA was extracted from. 
GGBN extension to DwC already has elements to deal with both of these.

**Comment by TaniaGLaity** [comment]
closed as sequences tab was removed
